%addpath(genpath('~/.matlab/R2011a/third-party/'));
%addpath(genpath('/scratch/vision/dineshj/Composite_concepts/Libraries/BasicLibraries/vlfeat-0.9.16/'));
%addpath(genpath('/scratch/vision/dineshj/Composite_concepts/Libraries/BasicLibraries/SVMs/liblinear-1.93/'));
%addpath(genpath('/scratch/vision/dineshj/Composite_concepts/Libraries/BasicLibraries/SVMs/libsvm-3.16/'));
%addpath(genpath('/scratch/vision/dineshj/Composite_concepts/Libraries/BasicLibraries/utils/'));
addpath(genpath('/scratch/vision/dineshj/Composite_concepts/Libraries/'));
%addpath(genpath('/scratch/vision/dineshj/Semantic_attributes/codes/TGLasso/'));
%addpath(genpath('/scratch/vision/dineshj/Semantic_attributes/codes/matlab_mtl/'));
%addpath(genpath('/scratch/vision/dineshj/Semantic_attributes/codes/MALSAR/'));
